notifications:
  email: false

node_js:
  - "0.12.17"
  - "4.6.1"
  - "6.9.0"

sudo: required

before_install: ./setup.sh

install: 
	- cd viajessinbarreas/ 
	- npm test

services:
  - mysql
  - mongodb


