language: node_js
notifications:
  email: false

node_js:
  - "0.12.17"
  - "4.6.1"
  - "6.9.0"

services:
  - mongodb
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
